[project]
name = "dspace-statistics-api"
version = "1.4.6-dev"
description = "A simple REST API to expose Solr view and download statistics for items, communities, and collections in a DSpace repository."
authors = [
    { name = "Alan Orth", email = "git@mjanja.mozmail.com" }
]

requires-python = ">= 3.10"

license = "GPL-3.0-only"
license-files = ["LICENSE.txt"]
dependencies = [
    "gunicorn==25.3.*",
    "falcon==4.2.*",
    "psycopg==3.3.*",
    "requests==2.34.*",
    "falcon-swagger-ui",
]

[project.urls]
repository = "https://github.com/ilri/dspace-statistics-api"
homepage = "https://github.com/ilri/dspace-statistics-api"

[tool.uv.sources]
falcon-swagger-ui = { git = "https://github.com/alanorth/falcon-swagger-ui", rev = "falcon3-update-swagger-ui" }

# See: https://docs.astral.sh/uv/concepts/build-backend/#using-the-uv-build-backend
[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "flake8==7.3.*",
    "isort==8.0.*",
    "pytest==9.0.*",
]

[tool.isort]
profile = "black"
line_length=88
